[env:esp32s3cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_build.partitions = huge_app.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=3

lib_deps =
    espressif/esp32-camera@^2.0.4
    lovyan03/LovyanGFX@^1.1.12
    bodmer/TJpg_Decoder@^1.1.0      ; JPEG decoder